"""Config."""

import os

# PATHS

INSTANCE_FILE_PATH = "./data/databases/all_table_infos.json"
INSTANCE_INDEX_PATH = "./data/databases/tables"
NLTK_DATA_PATH = "./nltk_data"
CHECKPOINTS_PATH = "./data/databases/checkpoints.db"

# Langsmith
LANGSMITH_PROJECT = "kdr"

# Model and service configuration
SEARCH_API_KEY = os.getenv("SEARCH_API_KEY", "")
if SEARCH_API_KEY:
    os.environ.setdefault("".join(["SERPER", "_API_KEY"]), SEARCH_API_KEY)

DEFAULT_LLM_API_KEY = os.getenv("DEFAULT_LLM_API_KEY", "")
DEFAULT_LLM_BASE_URL = os.getenv("DEFAULT_LLM_BASE_URL", "")
DEFAULT_CHAT_MODEL = os.getenv("DEFAULT_CHAT_MODEL", "chat-model-placeholder")
DEFAULT_VISION_MODEL = os.getenv("DEFAULT_VISION_MODEL", "vision-model-placeholder")
DEFAULT_EMBEDDING_MODEL = os.getenv(
    "DEFAULT_EMBEDDING_MODEL",
    "embedding-model-placeholder",
)

# Keep legacy names for modules outside kdr that may still import them.
OPENAI_API_KEY = DEFAULT_LLM_API_KEY
BASEURL_OPENAI = DEFAULT_LLM_BASE_URL
if OPENAI_API_KEY:
    os.environ.setdefault("OPENAI_API_KEY", OPENAI_API_KEY)

WRITER_MODEL = os.getenv("WRITER_MODEL", DEFAULT_CHAT_MODEL)
WRITER_API_KEY = os.getenv("WRITER_API_KEY", DEFAULT_LLM_API_KEY)
WRITER_BASEURL = os.getenv("WRITER_BASEURL", DEFAULT_LLM_BASE_URL)

CODER_MODEL = os.getenv("CODER_MODEL", DEFAULT_CHAT_MODEL)
CODER_API_KEY = os.getenv("CODER_API_KEY", DEFAULT_LLM_API_KEY)
CODER_BASEURL = os.getenv("CODER_BASEURL", DEFAULT_LLM_BASE_URL)

PLANNER_MODEL = os.getenv("PLANNER_MODEL", DEFAULT_CHAT_MODEL)
PLANNER_API_KEY = os.getenv("PLANNER_API_KEY", DEFAULT_LLM_API_KEY)
PLANNER_BASEURL = os.getenv("PLANNER_BASEURL", DEFAULT_LLM_BASE_URL)

ANALYZER_MODEL = os.getenv("ANALYZER_MODEL", DEFAULT_VISION_MODEL)
ANALYZER_API_KEY = os.getenv("ANALYZER_API_KEY", DEFAULT_LLM_API_KEY)
ANALYZER_BASEURL = os.getenv("ANALYZER_BASEURL", DEFAULT_LLM_BASE_URL)

EXTRACTOR_MODEL = os.getenv("EXTRACTOR_MODEL", DEFAULT_CHAT_MODEL)
EXTRACTOR_API_KEY = os.getenv("EXTRACTOR_API_KEY", DEFAULT_LLM_API_KEY)
EXTRACTOR_BASEURL = os.getenv("EXTRACTOR_BASEURL", DEFAULT_LLM_BASE_URL)

EVALUATION_MODEL = os.getenv("EVALUATION_MODEL", DEFAULT_CHAT_MODEL)
EVALUATION_API_KEY = os.getenv("EVALUATION_API_KEY", DEFAULT_LLM_API_KEY)
EVALUATION_BASEURL = os.getenv("EVALUATION_BASEURL", DEFAULT_LLM_BASE_URL)

EVALUATION_MODEL_NO_THINKING = os.getenv(
    "EVALUATION_MODEL_NO_THINKING",
    DEFAULT_CHAT_MODEL,
)
EVALUATION_NO_THINKING_API_KEY = os.getenv(
    "EVALUATION_NO_THINKING_API_KEY",
    DEFAULT_LLM_API_KEY,
)
EVALUATION_NO_THINKING_BASEURL = os.getenv(
    "EVALUATION_NO_THINKING_BASEURL",
    DEFAULT_LLM_BASE_URL,
)

EVALUATION_MODEL_SMALL = os.getenv("EVALUATION_MODEL_SMALL", DEFAULT_CHAT_MODEL)
EVALUATION_SMALL_API_KEY = os.getenv(
    "EVALUATION_SMALL_API_KEY",
    DEFAULT_LLM_API_KEY,
)
EVALUATION_SMALL_BASEURL = os.getenv(
    "EVALUATION_SMALL_BASEURL",
    DEFAULT_LLM_BASE_URL,
)

EMBEDDING_MODEL = DEFAULT_EMBEDDING_MODEL
EMBEDDING_API_KEY = os.getenv("EMBEDDING_API_KEY", DEFAULT_LLM_API_KEY)
BASEURL_EMBEDDING = os.getenv("EMBEDDING_BASEURL", DEFAULT_LLM_BASE_URL)
EMBEDDING_DIMENSIONS = 1024

MODEL_CONFIGS = {
    "writer": {
        "model": WRITER_MODEL,
        "api_key": WRITER_API_KEY,
        "base_url": WRITER_BASEURL,
    },
    "coder": {
        "model": CODER_MODEL,
        "api_key": CODER_API_KEY,
        "base_url": CODER_BASEURL,
    },
    "planner": {
        "model": PLANNER_MODEL,
        "api_key": PLANNER_API_KEY,
        "base_url": PLANNER_BASEURL,
    },
    "analyzer": {
        "model": ANALYZER_MODEL,
        "api_key": ANALYZER_API_KEY,
        "base_url": ANALYZER_BASEURL,
    },
    "extractor": {
        "model": EXTRACTOR_MODEL,
        "api_key": EXTRACTOR_API_KEY,
        "base_url": EXTRACTOR_BASEURL,
    }
}

SEED = 42
MAX_OUTPUT_RETRY = 2

# Supervisor
TOTAL_TOOL_CALL = 40

# Web Search
WEB_SEARCH_TOP_K = 5

# Knowledge Computing
CONCEPT_TOP_K = 5
INSTANCE_TOP_K = 5
INSTANCE_SELECTION_K = 1
INSTANCE_SCORE_THRESHOLD = -1.0  # FAISS uses cosine similarity by default
